version: 4.21.0-{branch}-{build}
image: Ubuntu2004
clone_depth: 1
cache:
  - /home/appveyor/.ccache

build_script:
- sh: >-
    git log > /tmp/gitlog.txt

    grep -q '\[ci reset\]' /tmp/gitlog.txt && rm -rf /home/appveyor/.ccache

    sudo apt-get update -qq

    sudo apt-get install -qq wget

    sudo wget https://raw.githubusercontent.com/fluxer/katana-ubuntu/master/katana.list -O /etc/apt/sources.list.d/katana.list

    sudo apt-get update -qq

    sudo apt-get install -qq cmake katie-dev katana-baseapps \
        katana-workspace xorg-dev zlib1g-dev libacl1-dev libattr1-dev \
        libarchive-dev libasound2-dev libatasmart-dev libavcodec-dev \
        libavformat-dev libavutil-dev libblkid-dev libdjvulibre-dev \
        libepub-dev libexiv2-dev libfreetype6-dev libssl-dev \
        libgettextpo-dev libgmp-dev libmms-dev libparted-dev \
        libqalculate-dev libspectre-dev libspeechd-dev libswscale-dev \
        libtag1-dev uuid-dev libudev-dev libvncserver-dev freerdp2-dev \
        libffmpegthumbnailer-dev libbz2-dev libtorrent-rasterbar-dev \
        xsltproc libdbusmenu-katie libpoppler-katie \
        ccache

    export PATH="/usr/lib/ccache/:$PATH"

    mkdir build

    cd build

    cmake ../ -Wno-dev

    make -j $(nproc || echo 1)
